apiVersion: iam.services.k8s.aws/v1alpha1
kind: RolePolicyAttachment
metadata:
  name: grafana-cloudwatch
spec:
  roleRef:
    from:
      name: grafana-irsa
  policyARN: arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
