apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: grafana-irsa
spec:
  name: grafana-irsa
  assumeRolePolicyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Federated": "arn:aws:iam::<ACCOUNT_ID>:oidc-provider/<OIDC>"
          },
          "Action": "sts:AssumeRoleWithWebIdentity",
          "Condition": {
            "StringEquals": {
              "<OIDC>:sub": "system:serviceaccount:monitoring:grafana",
              "<OIDC>:aud": "sts.amazonaws.com"
            }
          }
        }
      ]
    }

  policies:
    - name: grafana-inline-cloudwatch-eks
      policyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [

            // --- CloudWatch Metrics ---
            {
              "Effect": "Allow",
              "Action": [
                "cloudwatch:GetMetricData",
                "cloudwatch:GetMetricStatistics",
                "cloudwatch:ListMetrics"
              ],
              "Resource": "*"
            },

            // --- CloudWatch Logs ---
            {
              "Effect": "Allow",
              "Action": [
                "logs:DescribeLogGroups",
                "logs:DescribeLogStreams",
                "logs:GetLogEvents",
                "logs:StartQuery",
                "logs:GetQueryResults"
              ],
              "Resource": "*"
            },

            // --- EKS ReadOnly ---
            {
              "Effect": "Allow",
              "Action": [
                "eks:DescribeCluster",
                "eks:ListClusters",
                "eks:ListNodegroups",
                "eks:DescribeNodegroup",
                "eks:ListFargateProfiles",
                "eks:DescribeFargateProfile"
              ],
              "Resource": "*"
            }

          ]
        }
